version: "3.9"

services:
  db:
    image: postgres:12.6
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: ["postgres", "-c", "log_statement=all"]
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - '6379:6379'
      
volumes:
  redis_data:
  db_data:
